### ISSUE TITLE
Create new CoMP database

### ISSUE THREAD

**Issue by mgalloy** [NCAR/comp-pipeline#14]
Create new database schema and populate in pipeline.

- [x] create tables from definitions

Tables needing to be defined:

- [x] `comp_file`
- [x] `comp_eng`
- [x] `comp_cal`
- [x] `comp_sci`
- [x] `comp_level`
- [x] `comp_sw`
- [x] `comp_hw`
- [x] `comp_mission`

Tables needing to be populated:

- [x] `comp_file`
- [x] `comp_eng`
- [x] `comp_cal`
- [x] `comp_sci`
- [x] `comp_dynamics`
- [x] `comp_sw`
- [x] `comp_level`
- [x] `comp_mission`

Tables to be updated:

- [x] update `mlso_numfiles`

`comp_file` contains:

- line profile L1 files
- line center polarization/dynamics files
- quick invert, mean/median/sigma files (both waves and synoptic versions)

More files to be assimilated into database:
- [x] dynamics
- [x] polarization
- [x] average files
- [x] quick inverts

**Comment by mgalloy** [comment]
Tables needed:

* comp_file
* comp_img
* comp_eng
* comp_cal
* comp_sci
* comp_level
* comp_sw
* comp_hw
* comp_mission

**Comment by mgalloy** [comment]
How often should the `comp_sci` table be updated (KCor gives only one row per day right now)?

**Comment by mgalloy** [comment]
Database definition needs to be shown to @detoma and @StevenTomczyk for suggestions. We also need to update `mlso_numfiles` with @kolinski help.

**Comment by kolinski** [comment]
Write to mlso_numfiles table.  Coordinate with D. Kolinski (currently has cronjob updating num_comp_intensity_fullresgif and num_comp_polarization_fits).

Fields to update:
num_comp_intensity_fullresgif
num_comp_polarization_fits
num_comp_dynamics_fits
num_comp_meanmedian_fits
num_comp_quickinvert_fits

Since these fields are not wavelength dependent, put in the largest value (for instance, the number of 1074 polarization files if that wavelength has the most, or the number of 1074 synoptic means).  Another option is to put in the total number of files for each category for all wavelengths and types.

**Comment by mgalloy** [comment]
Add stray light coefficients to `comp_eng` table.

**Comment by mgalloy** [comment]
WIth the recent additions of the level 2 files, I believe this issue is closed. The `ucomp_db_clearday` routine also clears everything that should be cleared (some tables are not cleared such as `ucomp_sw`, `ucomp_mission`, and `ucomp_level`).
